//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordsCounterClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceCount")]
    public interface IServiceCount {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCount/CountWords", ReplyAction="http://tempuri.org/IServiceCount/CountWordsResponse")]
        System.Collections.Generic.Dictionary<string, int> CountWords(string fullText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCount/CountWords", ReplyAction="http://tempuri.org/IServiceCount/CountWordsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> CountWordsAsync(string fullText);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCountChannel : WordsCounterClient.ServiceReference1.IServiceCount, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCountClient : System.ServiceModel.ClientBase<WordsCounterClient.ServiceReference1.IServiceCount>, WordsCounterClient.ServiceReference1.IServiceCount {
        
        public ServiceCountClient() {
        }
        
        public ServiceCountClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCountClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCountClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCountClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, int> CountWords(string fullText) {
            return base.Channel.CountWords(fullText);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> CountWordsAsync(string fullText) {
            return base.Channel.CountWordsAsync(fullText);
        }
    }
}
